import React from "react";

export const metadata = {
  title: "NextJs Core Concept Home Page",
  description: "Generated by create next app",
};

const HomePage = () => {
  return (
    <div>
      <h1 className="text-3xl font-bold text-center">Welcome to Next.js</h1>
    </div>
  );
};

export default HomePage;
