import React from "react";

export const metadata = {
  title: "NextJs Core Concept Home Page",
  description: "Generated by create next app",
};

const HomePage = async () => {
 const res = await fetch("http://localhost:5000/posts");
  const data = await res.json();
  console.log(data);
  return (
    <div>
      <h1 className="text-3xl font-bold text-center">Welcome to Next.js</h1>
      <div>
        {
          data.posts?.map((post) => (
            <div key={post.id}>
              <h2 className="text-2xl font-bold">{post.title}</h2>
              <p>{post.views} views</p>
            </div>
          ))
        }
      </div>
    </div>
  );
};

export default HomePage;
